---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: sam-jenkins-node
  name: sam-jenkins-node
  namespace: sam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sam-jenkins-node
  strategy: {}
  template:
    metadata:
      creationTimestamp:
      labels:
        app: sam-jenkins-node
    spec:
      containers:
      - image: openjdk:8
        name: sam-jenkins-node
        resources: {}
        command:
          - /bin/sh
          - -c
          - apt-get update && apt-get install default-jre
          # - echo 'HellllllllllllloooooooooOOOOOOOOOOOOOO----------------------------*********************'
status: {}
...