---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: sam-jenkins-master
  namespace: sam
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: sam-jenkins-master
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: sam-jenkins-master
  name: sam-jenkins-master
  namespace: sam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sam-jenkins-master
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sam-jenkins-master
    spec:
      containers:
      - image: jenkins
        name: jenkins
        resources: {}
      #   volumeMounts:
      #   - mountPath: /var/lib/jenkins
      #     name: sam-master-volume  #name of the volume to mount on
      # volumes:
      #   - name: sam-master-volume
      #     persistentVolumeClaim:
      #       claimName: sam-master-claim
status: {}
