---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: sam-mysql
  namespace: sam
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    run: sam-mysql
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: sam-mysql
  name: sam-mysql
  namespace: sam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sam-mysql
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sam-mysql
    spec:
      containers:
      - image: mysql
        name: mysql
        resources: {}
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: password
        ports:
        - containerPort: 3306
          name: mysql
        resources: {}
      #   volumeMounts:
      #   - mountPath: /var/lib/mysql
      #     name: sam-mysql-volume  #name of the volume to mount on
      # volumes:
      # - name: sam-mysql-volume
      #   persistentVolumeClaim:
      #     claimName: sam-mysql-claim
status: {}
