---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: sam-jenkins-node
  namespace: sam
spec:
  ports:
  - port: 50000
    protocol: TCP
    targetPort: 50000
  selector:
    run: sam-jenkins-node
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: sam-jenkins-node
  name: sam-jenkins-node
  namespace: sam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sam-jenkins-node
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sam-jenkins-node
    spec:
      containers:
      - image: openjdk:8
        name: jenkins-node
        resources: {}
      #   volumeMounts:
      #   - mountPath: /var/lib/jenkins
      #     name: sam-node-volume  #name of the volume to mount on
      # volumes:
      #   - name: sam-node-volume
      #     persistentVolumeClaim:
      #       claimName: sam-node-claim
status: {}
